Name:           ros-indigo-ackermann-vehicle
Version:        0.1.1
Release:        0%{?dist}
Summary:        ROS ackermann_vehicle package

Group:          Development/Libraries
License:        Apache 2.0
URL:            http://wiki.ros.org/ackermann_vehicle
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-indigo-ackermann-vehicle-description
Requires:       ros-indigo-ackermann-vehicle-gazebo
BuildRequires:  ros-indigo-catkin

%description
ackermann_vehicle is a group of packages for simulating a vehicle with Ackermann
steering.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Fri Sep 26 2014 Jim Rothrock <jim.rothrock@wunderkammerlab.com> - 0.1.1-0
- Autogenerated by Bloom

* Thu Sep 18 2014 Jim Rothrock <jim.rothrock@wunderkammerlab.com> - 0.1.0-0
- Autogenerated by Bloom

